In [204]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import seaborn as sns

In [150]:
raw_data = pd.read_csv('creditcard.csv')

In [151]:
raw_data

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [206]:
data = raw_data.copy()



In [175]:
inputs = data.iloc[:,1:-1]
targets = data.iloc[:,-2:]
targets = targets.drop(['Amount'],axis=1)



In [201]:
inputs_random = inputs.sample(frac = 1)
targets_random = targets.sample(frac = 1)



In [34]:
target_1 = int(np.sum(targets_random))


In [156]:
target_0_counter = 0
nump_inputs_random = inputs_random.to_numpy()
nump_targets_random = targets_random.to_numpy()
nump_targets_random.shape[0]

284807

In [157]:
indices_to_remove = []

In [158]:
for i in range(nump_targets_random.shape[0]):
    if nump_targets_random[i] == 0:
        target_0_counter += 1
        if target_0_counter > target_1:
            indices_to_remove.append(i)           

In [33]:
inputs_balanced = np.delete(nump_inputs_random, indices_to_remove, axis=0)   
targets_balanced = np.delete(nump_targets_random, indices_to_remove, axis=0) 



array([[ 1.90220787e+00, -5.60857714e-01, -3.05793549e-01, ...,
        -2.35834213e-02, -3.87962156e-02,  5.99000000e+01],
       [ 2.21157524e+00, -1.04741614e+00, -8.95521909e-01, ...,
         5.70445263e-03, -6.73070257e-02,  5.99000000e+00],
       [ 1.30237651e+00, -1.32096325e+00,  7.31243494e-01, ...,
         2.07112564e-02,  3.28232201e-02,  8.66400000e+01],
       ...,
       [-1.03956841e+00,  1.29446758e+00, -6.76780773e-01, ...,
         5.23002064e-01,  1.46676645e-01,  3.86200000e+01],
       [-7.51495391e-01,  8.52878084e-01,  2.26956894e+00, ...,
        -4.86729019e-01, -3.86514052e-01,  1.33200000e+01],
       [ 1.43111838e+00, -9.95244226e-01,  8.46275547e-01, ...,
         4.43637255e-02,  3.94878611e-02,  3.85000000e+01]])

In [192]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(inputs_balanced, targets_balanced, train_size=0.8 , shuffle=True, random_state=20)


In [193]:
reg = LogisticRegression(max_iter=400)
oned_y_train = np.ravel(y_train)

reg.fit(x_train,oned_y_train)


LogisticRegression(max_iter=400)

In [194]:
reg.score(x_train,oned_y_train)

0.5730622617534943

In [176]:
reg.intercept_

array([0.06300976])

In [177]:
reg.coef_

array([[-0.14149324, -0.15352189,  0.03701635,  0.02636682,  0.01387438,
        -0.00584118, -0.23939952, -0.12581906,  0.05397729, -0.02768983,
         0.05969148, -0.13487625, -0.13520701,  0.06273762, -0.01297947,
        -0.0880214 , -0.07088484, -0.13484377,  0.08227927,  0.05526123,
         0.03288163,  0.08803612, -0.00447379,  0.22587089,  0.12035401,
         0.0007123 , -0.10352057,  0.16725352, -0.00028841]])

In [179]:
feature_name = inputs.columns
summary_table20 = pd.DataFrame(columns=['Feature Name'],data = feature_name)

In [180]:
summary_table20['Coefficient'] = np.transpose(reg.coef_)

In [181]:
summary_table20.index = summary_table20.index + 1
summary_table20.loc[0] = ['Intercept',reg.intercept_[0]]


In [182]:
summary_table20 = summary_table20.sort_values('Coefficient', ascending=False)
summary_table20.to_excel("summary_table20.xlsx")
summary_table20

Feature Name  Coefficient
24          V24     0.225871
28          V28     0.167254
25          V25     0.120354
22          V22     0.088036
19          V19     0.082279
0     Intercept     0.063010
14          V14     0.062738
11          V11     0.059691
20          V20     0.055261
9            V9     0.053977
3            V3     0.037016
21          V21     0.032882
4            V4     0.026367
5            V5     0.013874
26          V26     0.000712
29       Amount    -0.000288
23          V23    -0.004474
6            V6    -0.005841
15          V15    -0.012979
10          V10    -0.027690
17          V17    -0.070885
16          V16    -0.088021
27          V27    -0.103521
8            V8    -0.125819
18          V18    -0.134844
12          V12    -0.134876
13          V13    -0.135207
1            V1    -0.141493
2            V2    -0.153522
7            V7    -0.239400

In [195]:
reg.score(x_test,y_test)

0.5025380710659898